title: Mazharul Islam Tusar
description: >
  Ph.D. researcher in cybersecurity | AI/ML | Cloud | Privacy Systems

remote_theme: pages-themes/hacker@v0.2.0
markdown: kramdown

# Optional extras
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
